### ISSUE TITLE
Repository language sync

### ISSUE THREAD

**Issue by leonofre** [brenoalvs/monk#105]
Download language packs automatically from WordPress.org repository when activate languages.

**Comment by brenoalvs** [comment]
I figured out that we need call `wp_dropdown_languages()` function previously to be able to use `wp_download_language_packs()`.

We can use `wp_dropdown_languages()` to render `monk_default_language` field and then on the bottom of page load all translations files.

Or we can implement our own code to make it more cleaner.

References:
https://developer.wordpress.org/reference/functions/wp_dropdown_languages/
https://developer.wordpress.org/reference/functions/wp_download_language_pack/
