### ISSUE TITLE
Post returning from trash

### ISSUE THREAD

**Issue by chandonn-zz** [brenoalvs/monk#295]
The user may want to restore a post from trash. When this case happens with a translated post, the "returning one" keeps the translation data, but the other one doesn't recognize it, showing as a not translated post.

**Comment by leonofre** [comment]
In this case, the restored post show other posts on translation list, but the message of 'not translated' is displayed too.
![image](https://user-images.githubusercontent.com/19397230/29841730-f4564cd4-8cdc-11e7-8b04-aa9b17d70c99.png)
And if the post is updated the list return to normal.
