### ISSUE TITLE
UX: Post edit metabox reorganisation

### ISSUE THREAD

**Issue by zedejose** [brenoalvs/monk#357]
(Apologies for the sudden influx of issues, but I'm liking Monk more and more, and have suggestions)

The metabox on the post editing screen is not very intuitive to me, i.e. 

![screen shot 2017-11-16 at 12 13 37](https://user-images.githubusercontent.com/1371600/32891264-d076bc92-cac9-11e7-854c-fbed6784d4a2.png)

There's a confusion of labels, hierarchies, actions and information. It would seem to me that it could be better organised in something similar to:

Languages (metabox title)

- English (the post's language, not sure about the "Edit" link)
- Português: **post title** (and not just the language name, with link to the translation)
- Français: **post title** (and not just the language name, with link to the translation)
- (etc...)

Add a translation (label)
- Language (select from available)
- Add a new (blank) translation (radio)
- Add translation and copy current content (radio)
- Add (button)

Come to think of it, _Add translation and copy current content_ is possibly a new issue.

Thoughts?

**Comment by brenoalvs** [comment]
Don't worry we really like new issues! :)
I think those are nice changes.

Copy current content and post type configurations like page template, order, post formats and etc. is a must and a planned feature.
 
@chandon, @leonofre what do you guys think?

**Comment by brenoalvs** [comment]
@zedejose @chandonn @leonofre some ideas, what do you guys think?

![screen shot 2017-11-29 at 8 03 56 pm](https://user-images.githubusercontent.com/5307192/33401649-1ef8e0e4-d541-11e7-95a1-e1fb89d94474.png)

![screen shot 2017-11-29 at 8 07 26 pm](https://user-images.githubusercontent.com/5307192/33401650-1f1d565e-d541-11e7-9023-f928ebeb207f.png)

**Comment by zedejose** [comment]
You're all going to hate me soon... 😛 

Why **Copy post settings** and not **Copy post content and settings** or even **Copy this post's content and settings**? (and remember that "post" could be a CPT called something other than a "post", i.e. a "page" or an "event", and so on.)

**Comment by chandonn-zz** [comment]
Please comment anytime you want! 
We love feedback and really appreciate your ideas! We also want to know what are your thoughts about the design @brenoalvs proposed?

You do have a point, "Copy post settings" isn't general enough, we could change that label
What do you @brenoalvs  and @leonofre think?

**Comment by brenoalvs** [comment]
Sure, the message should contain the post type name.
`Copy %post_type% settings`

I'm opening a new issue where we can discuss about this specific feature. Let's focus here only in the post metabox. This message it's just a placeholder for now.
